version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=iban
      - POSTGRES_PASSWORD=iban
    ports:
      - '127.0.0.1:5432:5432'
  web:
    build: .
    env_file: common.env
    depends_on:
      - db
    ports:
      - '8000:8000'
    volumes:
      - .:/app:Z
    entrypoint:
      - /app/entrypoint.sh