# Generated by Django 2.1 on 2018-08-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0003_auto_20180814_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Suspended')], default=1, max_length=50),
        ),
    ]
