# Generated by Django 2.1 on 2018-08-14 21:11

import account_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('social_django', '0008_partial_timestamp'),
        ('account_management', '0004_auto_20180814_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='baseuser_ptr',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Suspended')], default=1),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'verbose_name': 'admin',
                'verbose_name_plural': 'admins',
                'proxy': True,
                'indexes': [],
            },
            bases=('account_management.baseuser',),
            managers=[
                ('objects', account_management.models.CustomUserManager()),
            ],
        ),
    ]
